### PR TITLE
models: add cnn-lstm-6a model

### PR DESCRIPTION
**Pull request by jirenmaa**
Added the cnn-lstm-6a model for experimentation. The model size is about 34 MB (keras, h5) for each model. Should we upload the model to a different platform, or should we keep it on GitHub?

### CODE REVIEW

**Comment by jirenmaa** [comment]
Maybe it's just me, i think we should upload the model to other separate platform like kaggle, thoughts on this suggestion?

**Comment by danrynr** [comment]
Later we can put it on google cloud storage bucket for ease of use. We can use kaggle if its easier to do.

**Comment by danrynr** [comment]
If we're using kaggle, can we set it to private? If so, is there a way we can access it through GPG keys or other keys?

**Review by danrynr — APPROVED** [review]
cool 👍

**Review by rizrmdhn — APPROVED** [review]

**Pull request merged**
